version: "3"
services:
  oneservice:
    container_name: oneservicecontainer
    image: oneimage
    build: ./one-service
    ports:
      - "9000:9000"
  twoservice:
    container_name: twoservicontainer
    image: twoimage
    build: ./two-service
    ports:
      - "9001:9000"
  nginx:
    container_name: nginxservicecontainer
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/public:/srv/www/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - oneservice
      - twoservice
